export const TEMPLATE_SELECT_UPDATE_TEMPLATES_LIST = 'TEMPLATE_SELECT_UPDATE_TEMPLATES_LIST';
export const TEMPLATE_SELECT_OPEN_MODAL = 'TEMPLATE_SELECT_OPEN_MODAL';
export const TEMPLATE_SELECT_CLOSE_MODAL = 'TEMPLATE_SELECT_CLOSE_MODAL';
