export const HOME_CONNECT_TO_SOCKET_BEGIN = 'HOME_CONNECT_TO_SOCKET_BEGIN';
export const HOME_CONNECT_TO_SOCKET_SUCCESS = 'HOME_CONNECT_TO_SOCKET_SUCCESS';
export const HOME_CONNECT_TO_SOCKET_FAILURE = 'HOME_CONNECT_TO_SOCKET_FAILURE';
export const HOME_CONNECT_TO_SOCKET_DISMISS_ERROR = 'HOME_CONNECT_TO_SOCKET_DISMISS_ERROR';
